repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.11
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        files: ^wt-[^/]+/src/
      - id: ruff-format
        files: ^wt-[^/]+/src/
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.25
    hooks:
      - id: uv-lock
