"""Tests for recompilation and diff checking of downstream workflows."""

from __future__ import annotations

from typing import Any

import pytest

from conftest import Workspace
from helpers.diff import format_diff_report, format_variance_analysis, parse_allowlist


class TestRecompile:
    """Test suite for recompiling downstream workflows."""

    def test_compile_succeeds(
        self,
        compiled_workspace: Workspace,
    ) -> None:
        """
        Verify that wt-compiler successfully compiles the workflow spec.

        This test ensures that the latest wt-compiler can process the
        downstream repo's spec.yaml without errors.
        """
        compile_result = compiled_workspace.compile_result
        assert compile_result is not None, "Compilation was not attempted"

        if not compile_result.success:
            pytest.fail(
                f"Compilation failed with exit code {compile_result.exit_code}\n"
                f"STDOUT:\n{compile_result.stdout}\n"
                f"STDERR:\n{compile_result.stderr}"
            )

    def test_no_unexpected_diff(
        self,
        compiled_workspace: Workspace,
        diff_allowlist: list[str | dict[str, Any]],
        show_diff_analysis: bool,
    ) -> None:
        """
        Verify that only allowlisted files have changes after recompilation.

        This test ensures that regenerating the code produces identical
        output except for expected dynamic files (README.md, pixi.lock, etc.).
        """
        compile_result = compiled_workspace.compile_result
        diff_result = compiled_workspace.diff_result

        # Skip if compilation failed (test_compile_succeeds will catch this)
        if compile_result is None or not compile_result.success:
            pytest.skip("Compilation failed, skipping diff check")

        assert diff_result is not None, "Diff check was not performed"

        # Show variance analysis if requested
        if show_diff_analysis and diff_result.variance_results:
            _, conditional_entries = parse_allowlist(diff_allowlist)
            analysis = format_variance_analysis(
                diff_result.variance_results, conditional_entries
            )
            print(f"\n{analysis}")

        if diff_result.has_unexpected_changes:
            report = format_diff_report(diff_result)
            pytest.fail(
                f"Unexpected changes detected after recompilation:\n\n"
                f"{report}\n\n"
                f"Allowlist: {diff_allowlist}\n"
                f"If these changes are expected, update the diff_allowlist in manifest.yaml"
            )

    def test_generated_path_exists(
        self,
        compiled_workspace: Workspace,
    ) -> None:
        """
        Verify that the expected generated package directory exists.

        This test ensures the compiler creates output in the expected location.
        """
        compile_result = compiled_workspace.compile_result
        repo_config = compiled_workspace.repo_config

        if compile_result is None or not compile_result.success:
            pytest.skip("Compilation failed, skipping path check")

        # If a generated_path was specified in the config, verify it exists
        if repo_config.generated_path:
            expected_path = compiled_workspace.clone_result.path / repo_config.generated_path
            assert expected_path.exists(), (
                f"Expected generated path does not exist: {expected_path}\n"
                f"Compiler output path: {compile_result.generated_path}"
            )

    def test_required_artifacts_exist(
        self,
        compiled_workspace: Workspace,
    ) -> None:
        """
        Verify that all required artifacts are generated.

        This test checks for the presence of key files that should always
        be generated by wt-compiler.
        """
        compile_result = compiled_workspace.compile_result

        if compile_result is None or not compile_result.success:
            pytest.skip("Compilation failed, skipping artifact check")

        generated_path = compile_result.generated_path
        if generated_path is None:
            pytest.skip("Generated path not determined")

        # Required top-level artifacts
        required_files = [
            "README.md",
            "Dockerfile",
            "pixi.toml",
        ]

        missing = []
        for file_name in required_files:
            if not (generated_path / file_name).exists():
                missing.append(file_name)

        if missing:
            pytest.fail(f"Missing required artifacts: {missing}")

        # Check for the package subdirectory (wf_* pattern)
        package_dirs = [d for d in generated_path.iterdir() if d.is_dir() and d.name.startswith("wf_")]
        assert len(package_dirs) == 1, (
            f"Expected exactly one wf_* package directory, found: {[d.name for d in package_dirs]}"
        )

        # Check for dags subdirectory
        package_dir = package_dirs[0]
        dags_dir = package_dir / "dags"
        assert dags_dir.exists(), f"Missing dags directory: {dags_dir}"

        # Check for tests directory
        tests_dir = generated_path / "tests"
        assert tests_dir.exists(), f"Missing tests directory: {tests_dir}"
